### ISSUE TITLE
api is not working to pull datapoints with datetime changes 

### ISSUE THREAD

**Issue by miguelcleon** [DendraScience/dendra-api-client-python#1]
I had to change this line of code:
https://github.com/DendraScience/dendra-api-client-python/blob/79e88075f0f50a98deadee9cecd05eee133e85e6/dendra_api_client.py#L344 

To: 
`time_last = df['t'].max()`
In order to pull datapoints through the API

**Comment by cbode** [comment]
Tested and confirmed bug.  However, the issue is dependent on whether you are using local or UTC time.  If local time is entered and the time column is set to `'t'`, you get an assertion error.   If UTC is entered and the time column is set to `'lt'`, you get an assertion error.   Solution: add a conditional based on `time_type`.
```
    if(time_type == 'utc'):
        time_col = 't'
    else:
        query.update({ 'time_local': "true" })
        time_col = 'lt'
     time_last = df[time_col].max() 
```
